"""crear_tablas

Revision ID: 1cb2a559e394
Revises: 
Create Date: 2025-01-31 12:27:07.080119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb2a559e394'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supermercado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('precio_kg', sa.String(length=50), nullable=False),
    sa.Column('url_imagen', sa.String(length=255), nullable=False),
    sa.Column('id_supermercado', sa.Integer(), nullable=False),
    sa.Column('nombre_busqueda', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_supermercado'], ['supermercado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producto_nombre_busqueda'), ['nombre_busqueda'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producto_nombre_busqueda'))

    op.drop_table('producto')
    op.drop_table('supermercado')
    # ### end Alembic commands ###
